> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [21]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [6]:
import numpy as np

# List of functions explained 
function1 = np.sum()  # (change this)
function2 = np.average()
function3 = np.concatenate
function4 = np.dot
function5 = np.square()

## Function 1 - np.sum()

returns the sum of elements in an array

In [12]:
# Example
import numpy as np
A= np.array([1, 2, 3])
print(np.sum(A))


6


A is an array containing 3 elements. printed below is the addition of the items present inside an array defind as A

In [14]:
# Example 2 addition of two arrays
A= np.array([1, 2, 3])
B= np.array([4, 5, 6])
A+B

array([5, 7, 9])

shown above is the addition of two numpy arrays

In [18]:
# Example 3 - breaking
A= np.array([1, 2, 3])
B= np.array([4, 5, 6])
return(np.add(A,B))

SyntaxError: 'return' outside function (<ipython-input-18-cdc592e4ed1b>, line 4)

return and print cant be used interchangebly, return can only be used when you are returning something from a function otherwise it has no meaning

this function can be used with pandas dataframe as well while combining two columns, also it can be used to sum the element inside the array and add two arrays.

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.ai/abhi-gangalwar/numpy-array-operations


'https://jovian.ai/abhi-gangalwar/numpy-array-operations'

## Function 2 - np.average()

it returns the average of the elements present inside arrays.

In [27]:
# Example 1 - working
A=([1,2,3])
average=np.average(A)
print('{} is an average of an elements contained in an array A'.format(average))

2.0 is an average of an elements contained in an array A


np.average() function returns the average of elements present inside an array.


In [28]:
# Example 2-
A= np.array([1,2,3])
B= np.array([1, 5, 3])
Y=A*B
print(np.average(Y))

6.666666666666667


given above is the average of multiplication of two arrays


In [29]:
# Example 3 - breaking 
A= np.array([1,2,3])
B= np.array([1, 5, 3])
Y=A*B
print(np.average[Y])

TypeError: 'function' object is not subscriptable

method can not be called with [], for calling it one needs to use ()

this funcation is useful while calculating the average or mean from arrays

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "abhi-gangalwar/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/abhi-gangalwar/numpy-array-operations


'https://jovian.ai/abhi-gangalwar/numpy-array-operations'

## Function 3- np.concatenate

this funcation can combine two or more arrays

In [83]:
# Example 1 - 
A= np.array([1,2,3])
B= np.array([1, 5, 3])
Y= np.concatenate((A,B), axis=0)
Y.shape, Y


((6,), array([1, 2, 3, 1, 5, 3]))

axis 0 will add elements in a row of array


In [84]:
# Example 2 - adding the output array after performing two two existing arrays
import numpy as np
A= np.array([[1, 2, 3], [1, 2, 3]])
B= np.array([[1, 5,3 ], [2,5,7]])

In [85]:
A.shape, B.shape

((2, 3), (2, 3))

In [88]:
Y=np.concatenate((A,B), axis=1)
Y.shape, Y

((2, 6),
 array([[1, 2, 3, 1, 5, 3],
        [1, 2, 3, 2, 5, 7]]))

axis 1 will add two rays along columns

In [91]:
# Example 3 -
A= ([[1, 2, 3], [5,6,7]])
B= ([1,4,7])
np.concatenate((A,B), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

for concatenating two arrays both the arrays should have similar dimentions.

this function helps to combine two or more arrays into a single array either by column side or row side

In [92]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "abhi-gangalwar/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/abhi-gangalwar/numpy-array-operations


'https://jovian.ai/abhi-gangalwar/numpy-array-operations'

## Function 4 - np.dot()
this function first multiply two arrays and then add them

In [95]:
# Example 1 - working
import numpy as np
A= np.array([[1,2,3], [2,3,4]])
B= np.array([2,3,4])
B.reshape(3,1)
np.dot(A,B)

array([20, 29])

this is the dot product of two matrices

In [106]:
# Example 2 - alternate way of doing above example
A= np.array([[1,2,3], [2,3,4]])
B= np.array([2,3,4])

B.reshape(3,1)
A@B

array([20, 29])

Explanation about example

In [114]:
# Example 3 - breaking (to illustrate when it breaks)
A= np.array([[1,2,3], [2,3,4]])
B= np.array([[2,3,4], [1, 4, 7]])
A.shape, B.shape
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

No. of column of one matrix and no. of rows of another matrix needs to be equal

This funcation provides a way for matrix multiplication

In [115]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "abhi-gangalwar/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/abhi-gangalwar/numpy-array-operations


'https://jovian.ai/abhi-gangalwar/numpy-array-operations'

## Function 5 - np.square()

returns the square of elements present inside array

In [116]:
# Example 1 - working
A= np.array([1,2,3])
np.square(A)

array([1, 4, 9])

function above has returned the squares of element in an array

In [118]:
# Example 2 - adding the elements inside array and then calculating the square
A= np.array([1,2,3])
X= np.sum(A)
np.square(X)

36

function mentioned above has provided the squares of sum of two arrays

In [119]:
# Example 3 - breaking (to illustrate when it breaks)
#Not able to think how to break this function

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'